Repository S-Qudus/Tudee, pull requests merged in 2025-07, with the labels that each got.

#72 add wrap service call
  app/src/main/java/com/qudus/tudee/data/service/CategoryServiceImpl.kt
  app/src/main/java/com/qudus/tudee/data/service/TaskServiceImpl.kt
  app/src/main/java/com/qudus/tudee/data/util/WrapCall.kt
  app/src/main/java/com/qudus/tudee/domain/exception/CategoryException.kt
  app/src/main/java/com/qudus/tudee/domain/exception/TaskExecption.kt
  app/src/main/java/com/qudus/tudee/ui/exception/ExceptionHandler.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, feature

#65 Feature/create and edit category screen
  app/build.gradle.kts
  app/src/main/java/com/qudus/tudee/app/di/uiModule.kt
  app/src/main/java/com/qudus/tudee/data/mapper/CategoryMapper.kt
  app/src/main/java/com/qudus/tudee/data/service/CategoryServiceImpl.kt
  app/src/main/java/com/qudus/tudee/domain/exception/CategoryException.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/color/TudeeColors.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/color/darkThemeColor.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/color/lightThemeColor.kt
  app/src/main/java/com/qudus/tudee/ui/exception/ExceptionHandler.kt
  app/src/main/java/com/qudus/tudee/ui/screen/addCategoryScreen/AddCategoryEvent.kt
  app/src/main/java/com/qudus/tudee/ui/screen/addCategoryScreen/AddCategoryScreen.kt
  app/src/main/java/com/qudus/tudee/ui/screen/addCategoryScreen/AddCategoryScreenViewModel.kt
  app/src/main/java/com/qudus/tudee/ui/screen/addCategoryScreen/AddCategoryUiState.kt
  app/src/main/java/com/qudus/tudee/ui/screen/addCategoryScreen/CategoryInteraction.kt
  app/src/main/java/com/qudus/tudee/ui/screen/addCategoryScreen/DahsedBorder.kt
  app/src/main/java/com/qudus/tudee/ui/screen/editCategoryScreen/EditCategoryEvent.kt
  app/src/main/java/com/qudus/tudee/ui/screen/editCategoryScreen/EditCategoryScreen.kt
  app/src/main/java/com/qudus/tudee/ui/screen/editCategoryScreen/EditCategoryScreenViewModel.kt
  app/src/main/java/com/qudus/tudee/ui/screen/editCategoryScreen/EditCategoryUiState.kt
  app/src/main/java/com/qudus/tudee/ui/state/CategoryUiState.kt
  app/src/main/java/com/qudus/tudee/ui/util/UiImage.kt
  app/src/main/res/drawable/icon_menu_circle.xml
  app/src/main/res/drawable/icon_upload.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#75 Feature/categories screen
  app/src/main/java/com/qudus/tudee/app/di/uiModule.kt
  app/src/main/java/com/qudus/tudee/data/service/TaskServiceImpl.kt
  app/src/main/java/com/qudus/tudee/domain/service/TaskService.kt
  app/src/main/java/com/qudus/tudee/ui/mapper/CategoryMapper.kt
  app/src/main/java/com/qudus/tudee/ui/screen/categories/CategoriesScreen.kt
  app/src/main/java/com/qudus/tudee/ui/screen/categories/CategoriesUiState.kt
  app/src/main/java/com/qudus/tudee/ui/screen/categories/CategoriesViewModel.kt
  app/src/main/res/drawable/icon_add_button.xml
  app/src/main/res/drawable/icon_add_category.xml
  app/src/main/res/values/splash_screen.xml
  app/src/main/res/values/strings.xml
Labels: feature

#91 UI Cleanup and Refactor
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/CategoryTaskComponent.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/DatePicker.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/HeaderTitle.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/MonthNavigationHeader.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/NoTasks.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/TabBar.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/TaskListSection.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/TaskTabItem.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/TudeeChip.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/priority/PriorityBadge.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/priority/PrioritySelector.kt
  app/src/main/java/com/qudus/tudee/ui/designSystem/component/taskComposable/TaskSection.kt
  app/src/main/java/com/qudus/tudee/ui/mapper/StateMapper.kt
  app/src/main/java/com/qudus/tudee/ui/mapper/TaskMapper.kt
  app/src/main/java/com/qudus/tudee/ui/mapper/TasksScreenMapper.kt
  app/src/main/java/com/qudus/tudee/ui/mapper/mapper.kt
  app/src/main/java/com/qudus/tudee/ui/navigation/TudeeNavGraph.kt
  app/src/main/java/com/qudus/tudee/ui/screen/ViewTasksByCategory/ViewTaskScreen.kt
  app/src/main/java/com/qudus/tudee/ui/screen/ViewTasksByCategory/ViewTaskState.kt
  app/src/main/java/com/qudus/tudee/ui/screen/ViewTasksByCategory/composabl/TaskItem.kt
  app/src/main/java/com/qudus/tudee/ui/screen/addTask/AddTaskScreen.kt
  app/src/main/java/com/qudus/tudee/ui/screen/editTask/EditTaskViewModel.kt
  app/src/main/java/com/qudus/tudee/ui/screen/taskEditor/TaskScreenContent.kt
  app/src/main/java/com/qudus/tudee/ui/screen/taskEditor/composable/PriorityChip.kt
  app/src/main/java/com/qudus/tudee/ui/screen/task_details/TaskDetailsScreen.kt
  app/src/main/java/com/qudus/tudee/ui/screen/task_details/TaskDetailsViewModel.kt
  app/src/main/java/com/qudus/tudee/ui/screen/task_details/components/TaskStatusAndPrioritySection.kt
  app/src/main/java/com/qudus/tudee/ui/screen/task_details/components/TaskStatusBadge.kt
  app/src/main/java/com/qudus/tudee/ui/screen/tasksScreen/TasksScreen.kt
  app/src/main/java/com/qudus/tudee/ui/screen/tasksScreen/TasksScreenContent.kt
  app/src/main/java/com/qudus/tudee/ui/screen/tasksScreen/state/TasksUiState.kt
  app/src/main/java/com/qudus/tudee/ui/screen/tasksScreen/viewModel/TaskViewModel.kt
  app/src/main/java/com/qudus/tudee/ui/state/PriorityUiState.kt
  app/src/main/java/com/qudus/tudee/ui/state/StateUiState.kt
  app/src/main/java/com/qudus/tudee/ui/state/TaskStateUiState.kt
  app/src/main/java/com/qudus/tudee/ui/state/TaskStatusUiState.kt
  app/src/main/java/com/qudus/tudee/ui/state/TaskUiState.kt
  app/src/main/java/com/qudus/tudee/ui/util/PriorityHelpers.kt
Labels: bug
